spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/DB_FS_ORDER
      host: localhost
      port: 27017
      database: DB_FS_ORDER
      repositories:
        enabled: true
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/